### ISSUE TITLE
As a user, I want to log in using my credentials so that I can access the appropriate dashboard.

### ISSUE THREAD

**Issue by Sibayan-ShainahGrace** [CCS112Organization/Product-Management-#33]
Acceptance Criteria:

- There should be input fields for username and password to log in.
- Upon successful login, Admins are redirected to the admin dashboard, while customers are redirected to the front store.
- If login fails, an error message should be displayed to the user.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the login method in AuthController to include the user's role in the response. This allows the frontend to determine whether the user is an admin or a customer.

You can review changes in this commit: https://github.com/lkilu6456546/CCS112Organization-E-Commerce-Platform-33/commit/8309ce4c9dbd6c00922e2b73d701e9548374926c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
